#define IDH_OTHERS			1
#define IDH_ENABLED			2
#define IDH_PLAYSOUNDS		3
#define IDH_UNSNAP_FILE		4
#define IDH_BROWSE_UNSNAP	5
#define IDH_SNAP_FILE		6
#define IDH_BROWSE_SNAP		7
#define IDH_TOGGLEKEYS		8
#define IDH_WIN_THRESH		9
#define IDH_SCREEN_THRESH	10
#define IDH_GENERALL		11
#define IDH_SNAPTOL			12
#define IDH_DESKTOP			13
#define IDH_SOUNDS			14
#define IDH_SELF            15
#define IDH_SNAPMDI			16
#define IDH_QUIETFAST		17
#define IDH_INSIDES			18
#define IDH_INVTOGGLE		19
#define IDH_ADVL			20
#define IDH_PLAY			21
#define IDH_CROPTOP			22
#define IDH_HIDEICON		23
#define IDH_VCENTER			24
#define IDH_HCENTER			25
#define IDH_KEPT			26