//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by snapit.rc
//
#define IDAPPLY                         2
#define IDC_CLEAR                       3
#define IDC_APPLY                       4
#define IDC_SAVE                        4
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDC_MYHAND                      104
#define IDS_THRESHOLD_ERROR             104
#define IDM_EXIT                        105
#define IDS_SELF                        105
#define IDS_HELLO                       106
#define IDS_OTHERS                      106
#define IDS_DESKTOP                     107
#define IDS_VCENTER                     108
#define IDI_SNAPIT                      109
#define IDS_STRING109                   109
#define IDS_HCENTER                     109
#define IDT_MYTRAY                      110
#define IDS_ENABLED                     110
#define IDS_PLAYSOUNDS                  111
#define IDS_UNSNAP_FILE                 112
#define IDS_BROWSE_UNSNAP               113
#define IDS_SNAP_FILE                   114
#define IDS_BROWSE_SNAP                 115
#define IDS_TOGGLEKEYS                  116
#define IDS_SCREEN_THRESH               117
#define IDS_WIN_THRESH                  118
#define IDS_SNAPTOL                     119
#define IDS_GENERALL                    120
#define IDS_SOUNDS                      121
#define IDS_SNAPMDI                     122
#define IDS_QUIETFAST                   123
#define IDS_INSIDES                     124
#define IDS_INVTOGGLE                   125
#define IDS_ADVL                        126
#define IDS_PLAY                        127
#define IDS_CROPTOP                     128
#define IDC_SNAPIT                      129
#define IDS_HIDEICON                    130
#define IDS_KEPT                        131
#define IDS_CENTERED                    132
#define IDS_STRING132                   132
#define IDR_SYSMENU                     133
#define IDS_CROP_RGN                    133
#define IDS_AUTOLINEUP                  134
#define IDS_CHECK_HORIZONTAL            135
#define IDI_DISABLED                    136
#define IDS_CHECK_VERTICAL              136
#define IDD_ABOUT                       137
#define IDS_H_NUM_EVEN                  137
#define IDS_H_PIXELS_BTWN               138
#define IDI_SPEAKER                     143
#define IDI_SNAP_TOS                    144
#define IDD_GENERAL                     168
#define IDD_SOUNDS                      169
#define IDI_ENABLED                     170
#define IDI_ARROWSLOGO                  178
#define IDR_WHAT                        200
#define IDM_WHAT                        201
#define IDR_WHAT3                       201
#define IDB_PAYPAL                      204
#define IDI_PLAY                        208
#define IDI_STOP                        209
#define IDD_ADVANCED                    211
#define IDI_XPDISABLED                  215
#define IDI_ICON1                       217
#define IDI_XPENABLED                   217
#define IDM_DEBUG                       218
#define IDI_XPENABLED1                  218
#define IDD_DEBUG                       219
#define ID_NOTIFY_ADD                   220
#define IDD_GRID                        220
#define ID_ADD_ALARMMESSAGE             221
#define ID_ADD_BEACONMESSAGE            222
#define ID_ADDMESSAGE_TELEMETRYMESSAGE  223
#define ID_ADDMESSAGE_TRACKING          224
#define ID_Menu                         225
#define ID_NOTIFY_CUT                   226
#define ID_NOTIFY_COPY                  227
#define IDR_MENU1                       228
#define IDR_COPY                        228
#define IDI_ICON2                       231
#define IDS_DEBUG_MSG                   500
#define IDS_STRING501                   501
#define IDS_STRING502                   502
#define IDS_STRING503                   503
#define IDS_STRING504                   504
#define IDS_STRING505                   505
#define IDS_STRING506                   506
#define IDS_STRING507                   507
#define IDS_STRING508                   508
#define IDS_STRING509                   509
#define IDS_STRING134                   510
#define IDS_STRING511                   511
#define IDS_STRING512                   512
#define IDS_STRING513                   513
#define IDS_STRING514                   514
#define IDS_STRING515                   515
#define IDS_STRING520                   516
#define IDS_STRING521                   517
#define IDS_STRING530                   518
#define IDS_STRING531                   519
#define IDS_STRING532                   520
#define IDS_STRING533                   521
#define IDS_STRING133                   522
#define IDS_STRING517                   523
#define IDS_STRING518                   524
#define IDS_STRING519                   525
#define IDS_STRING522                   526
#define IDS_STRING523                   527
#define IDS_STRING524                   528
#define IDS_STRING525                   529
#define IDS_STRING526                   530
#define IDS_STRING527                   531
#define IDS_STRING528                   532
#define IDS_STRING529                   533
#define IDS_STRING135                   534
#define IDS_STRING535                   535
#define IDS_STRING136                   536
#define IDC_THRESH                      1001
#define IDC_WIN_THRESH                  1001
#define IDC_SCREEN_THRESH               1002
#define IDC_DESKTOP                     1013
#define IDC_SELF                        1014
#define IDC_OTHERS                      1015
#define IDC_ENABLED                     1016
#define IDC_HCENTER                     1017
#define IDC_VCENTER                     1018
#define IDC_HCENTER2                    1019
#define IDC_CENTERED                    1019
#define IDC_PLAYSOUNDS                  1026
#define IDC_UNSNAP_FILE                 1029
#define IDC_BROWSE_UNSNAP               1030
#define IDC_SNAP_FILE                   1031
#define IDC_BROWSE_SNAP                 1032
#define IDC_TOGGLEKEYS                  1039
#define IDC_LINK                        1041
#define IDC_THRESH_SPIN                 1047
#define IDC_WIN_THRESH_SPIN             1047
#define IDC_SCREEN_THRESH_SPIN          1048
#define IDC_SNAPATL                     1049
#define IDC_PIXELSL                     1050
#define IDC_TOGGLEKEYL                  1051
#define IDC_GENERALL                    1052
#define IDC_SNAPATL2                    1053
#define IDC_SNAPFILEL                   1054
#define IDC_UNSNAPFILEL                 1055
#define IDC_CHOSEL                      1056
#define IDC_SOUNDSL                     1057
#define IDC_PAYPAL                      1062
#define IDC_EMAIL                       1063
#define IDC_PIXELSL2                    1064
#define IDC_SNAPMDI                     1069
#define IDC_TESTSNAPSOUND               1070
#define IDC_TESTSNAPSOUND2              1070
#define IDC_TESTUNSNAPSOUND             1071
#define IDC_QUIETFAST                   1072
#define IDC_INSIDES                     1074
#define IDC_INVTOGGLE                   1075
#define IDC_ADVL                        1076
#define IDC_CROPTOP                     1077
#define IDC_CROPTOPL                    1078
#define IDC_CROPTOP2L                   1079
#define IDC_HIDEICON                    1080
#define IDC_CROPTOPC                    1081
#define IDC_KEPT                        1083
#define IDC_MSGLIST                     1084
#define IDC_CROP_RGN                    1085
#define IDC_AUTOLINEUP                  1088
#define IDC_CHECK_HORIZONTAL            1089
#define IDC_CHECK_VERTICAL              1090
#define IDC_RADIO_H_EVEN                1091
#define IDC_RADIO_H_PIXELS              1092
#define IDC_RADIO_H_SINGLE              1093
#define IDC_RADIO_V_EVEN                1094
#define IDC_RADIO_V_PIXELS              1095
#define IDC_RADIO_V_SINGLE              1096
#define IDC_H_NUM_EVEN                  1097
#define IDC_H_PIXELS_BTWN               1099
#define IDC_PLAY_SNAP                   1099
#define IDC_H_PIXELS_FROM_TOP           1100
#define IDC_PLAY_UNSNAP                 1100
#define IDC_V_NUM_EVEN                  1101
#define IDC_CHECK2                      1101
#define IDC_V_PIXELS_BTWN               1102
#define IDC_V_PIXELS_FROM_LEFT          1103
#define IDM_SETTINGS                    32772
#define Enabled                         32773
#define IDS_ENABLED_TIP                 32774
#define IDS_DISABLED_TIP                32775
#define ID_ENABLEWINDOWSNAPPING         32776
#define IDM_COPY                        32785
#define ID_NOTHIN_COPY                  32787
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
