#ifndef SNAP_TYPES_INCLUDED

#define SNAP_TYPES_INCLUDED

#define SNAPT_DESKTOP  1
#define SNAPT_SELF     2
#define SNAPT_OTHERS   4
#define SNAPT_VCENTER  8
#define SNAPT_HCENTER  16
#define SNAPT_NONE	   0
#define SNAPT_ANY_SCREEN (SNAPT_DESKTOP|SNAPT_VCENTER|SNAPT_HCENTER)

#endif